# docker-compose.yml
# You can remove the version line as it's deprecated

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: Admin
      RABBITMQ_DEFAULT_PASS: Admin
    networks:
      - saasnet

  api-gateway:
    build:
      context: ./SaaS.ApiGetway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - auth-service
      - session-service
      - analytics-service
    networks:
      - saasnet

  auth-service:
    build:
      context: ./Microservice.AuthService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
    - RabbitMq__HostName=rabbitmq
    - RabbitMq__UserName=Admin
    - RabbitMq__Password=Admin
    networks:
      - saasnet

  session-service:
    build:
      context: ./Microservice.Session
      dockerfile: Dockerfile
    ports:
      - "5002:5002"  # HTTP
      - "7002:7002"  # gRPC
    networks:
      - saasnet

  analytics-service:
    build:
      context: ./Microservice.Analytics
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    networks:
      - saasnet

  tech-ciph:
    build:
      context: /home/hafiz/techciph/CipherNetSecurity
      dockerfile: Dockerfile
    ports:
      - "5051:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - saasnet

networks:
  saasnet:
    driver: bridge
